name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Check out thhe repository code
        uses: actions/checkout@v4
      - run: |
          #build image
          docker build -t seth-file-upload-blazor .
          #run image
          docker run -d seth-file-upload-blazor
          echo "made it to the end"
          #run image
          docker run -d \
          -p 1112:8080 \
          --name seth-file-upload-blazor \
          seth-file-upload-blazor
          echo "Made it to the end!!!"



